title: Code Stack
description: >-
  One stop shop for SOLIDWORKS API, Desktop, Web and Mobile 
  software development code examples and tips & tricks
email: codestack.net@gmail.com
theme: minima
name: CodeStack Library
markdown: kramdown
baseurl: /site
url: https://www.codestack.net
permalink: /:title
    
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]
    
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap