title: Code Stack
description: >-
  One stop shop for SOLIDWORKS API, Desktop, Web and Mobile 
  software development code examples and tips & tricks
email: codestack.net@gmail.com
theme: minima
name: CodeStack
markdown: kramdown
baseurl: /site
permalink: /:title

header_pages:
  - web-development/index.md
  - web-services/index.md
  
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]
    
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap